### ISSUE TITLE
20bn Jester Dataset 

### ISSUE THREAD

**Issue by ooice** [udacity/CVND---Gesture-Recognition#10]
Hi, I have downloaded the 20bn jester dataset from their website, but I don't know how to extract it. Where or how should I insert the command "cat 20bn-jester-v1-?? | tar zx"? Sorry, I do not know whether this is the right channel for me to ask but I hope you can help me with this. Was figuring out how to solve this for days as I am very unfamiliar with all of these. Thank you.

**Comment by eleow** [comment]
Do this in the unix shell/terminal/command prompt, and navigate to the directory where you downloaded the jester dataset files to.
If you are in Windows, then you will also need to download gnuWin32 ports of 'cat' and 'tar'.
http://gnuwin32.sourceforge.net/packages/coreutils.htm
and http://gnuwin32.sourceforge.net/packages/gtar.htm

**Comment by TechSari** [comment]
You still can use gitbash to extract the files, just navigate to the folder where you downloaded the files and then right-click and select  gitbash, add the command in 20bn website as it is and be patient  from there

**Comment by SagnikD95** [comment]
I tried it terminal but returns "Unrecognized archive format". Only the 00 file worked, rest all failed.
