### ISSUE TITLE
Files in the Jester datatset have no extension.

### ISSUE THREAD

**Issue by premvijay2306** [udacity/CVND---Gesture-Recognition#8]
I am trying to extract the dataset given on the link: https://20bn.com/datasets/jester

I am unable to extract these files as they have no extension. I tried using tar and also what they have mentioned on their website, i.e.,

cat 20bn-jester-v1-?? | tar zx

Please assist.

**Comment by jiamingNo1** [comment]
@premvijay2306 download all the 22 documents and then do this order

**Comment by ooice** [comment]
@jiamingNo1 how to do it? where to type the command?
