### ISSUE TITLE
when run train.py, got "IndexError: list index out of range"

### ISSUE THREAD

**Issue by iamyubin** [udacity/CVND---Gesture-Recognition#9]
Hi, everyone, when I run train.py, I got a  error as follow:
---------
(base) root@bf5f0cf0f3d5:/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master# python train.py --config configs/config_quick_testing.json --use_gpu=False
=> Output folder for this run -- jester_conv_4_classes
 > Using 8 processes for data loader.
 > Training is getting started...
 > Training takes 1 epochs.
 > Current LR : 0.001
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    main()
  File "train.py", line 185, in main
    val_loss, val_top1, val_top5 = validate(val_loader, model, criterion)
  File "train.py", line 257, in validate
    for i, (input, target) in enumerate(val_loader):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 38, in __getitem__
    img_paths = self.get_frame_names(item.path)
  File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 73, in get_frame_names
    frame_names += [frame_names[-1]] * (num_frames_necessary - num_frames)
IndexError: list index out of range
------
I don't know what's wrong, I did not change any code. I'm very appreciated if anyone can give me some advice.

**Comment by inkzk** [comment]
Hey, do you get the jester dataset? Could you please share the data?

**Comment by iamyubin** [comment]
> Hey, do you get the jester dataset? Could you please share the data?

The dataset can be download from the website https://20bn.com/datasets/jester/v1#download.

**Comment by eleow** [comment]
I encountered the same issue and finally managed to trace the problem. It is because num_frames = 0
In my case, it was because 'path' that was sent to get_frame_names was wrong... which was because train_data_csv's first column (folder name of the images) was being read as a float eg 100173 read as 100173.0
Another cause is if the folder really does not exist

**Comment by ankit-aglawe** [comment]
I'm also facing the same issue. If anyone got the solution, please do let us know.

**Comment by ghost** [comment]
Hi there, has anyone solved this issue? Would really appreciate the help here

**Comment by eleow** [comment]
> I encountered the same issue and finally managed to trace the problem. It is because num_frames = 0
> In my case, it was because 'path' that was sent to get_frame_names was wrong... which was because train_data_csv's first column (folder name of the images) was being read as a float eg 100173 read as 100173.0
> Another cause is if the folder really does not exist

Did this work for you @iAnkeet and @AAsyrf ?

**Comment by ghost** [comment]
> > I encountered the same issue and finally managed to trace the problem. It is because num_frames = 0
> > In my case, it was because 'path' that was sent to get_frame_names was wrong... which was because train_data_csv's first column (folder name of the images) was being read as a float eg 100173 read as 100173.0
> > Another cause is if the folder really does not exist
> 
> Did this work for you @iAnkeet and @AAsyrf ?

I managed to fix the error by redownloading and extracting the dataset. After that it worked fine for me.

**Comment by vnt1537** [comment]
@eleow I tried to print the 'frame_names' for which num_frames is == 0 and when I check the Jester  folder, so then have images inside. So what's the error here?

**Comment by ZhiguangLiuGithub** [comment]
> ## Hi, everyone, when I run train.py, I got a error as follow:
> (base) root@bf5f0cf0f3d5:/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master# python train.py --config configs/config_quick_testing.json --use_gpu=False
> => Output folder for this run -- jester_conv_4_classes
> 
> > Using 8 processes for data loader.
> > Training is getting started...
> > Training takes 1 epochs.
> > Current LR : 0.001
> > Traceback (most recent call last):
> > File "train.py", line 328, in 
> > main()
> > File "train.py", line 185, in main
> > val_loss, val_top1, val_top5 = validate(val_loader, model, criterion)
> > File "train.py", line 257, in validate
> > for i, (input, target) in enumerate(val_loader):
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in **next**
> > return self._process_next_batch(batch)
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
> > raise batch.exc_type(batch.exc_msg)
> > IndexError: Traceback (most recent call last):
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in 
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 38, in **getitem**
> > img_paths = self.get_frame_names(item.path)
> > File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 73, in get_frame_names
> > frame_names += [frame_names[-1]] * (num_frames_necessary - num_frames)
> > IndexError: list index out of range
> 
> I don't know what's wrong, I did not change any code. I'm very appreciated if anyone can give me some advice.

hi, have you solved the problem? I have the same question, my email: zhiguang8@126.com

**Comment by AAsyrf** [comment]
Hi @eleow, is there any way for me to contact you to ask about your project that was pulled from this one?

**Comment by ghost** [comment]
Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?

**Comment by ZhiguangLiuGithub** [comment]
> Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?

hi, what's the problem?

**Comment by ghost** [comment]
> > Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?
> 
> hi, what's the problem?

I've trained my model using 20 epochs but, and if I am not mistaken, it should save all of that to model_best_all.pth.tar (I am using the config_all.json file). But when I run webcam.py, it gives me this:

Using GPU for inference
=> loaded checkpoint './model_best_all.pth.tar' (**epoch 1**)
[INFO] Attemping to start video stream...
[INFO] Video stream started...


Does this mean that it only has the results from the 1st epoch? If so, why is that?

**Comment by ZhiguangLiuGithub** [comment]
> > > Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?
> > 
> > 
> > hi, what's the problem?
> 
> I've trained my model using 20 epochs but, and if I am not mistaken, it should save all of that to model_best_all.pth.tar (I am using the config_all.json file). But when I run webcam.py, it gives me this:
> 
> Using GPU for inference
> => loaded checkpoint './model_best_all.pth.tar' (**epoch 1**)
> [INFO] Attemping to start video stream...
> [INFO] Video stream started...
> 
> Does this mean that it only has the results from the 1st epoch? If so, why is that?

please check whether do you run the 'config_quick_testing.json' ? I rember that this file's epoch is 1.


> > > Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?
> > 
> > 
> > hi, what's the problem?
> 
> I've trained my model using 20 epochs but, and if I am not mistaken, it should save all of that to model_best_all.pth.tar (I am using the config_all.json file). But when I run webcam.py, it gives me this:
> 
> Using GPU for inference
> => loaded checkpoint './model_best_all.pth.tar' (**epoch 1**)
> [INFO] Attemping to start video stream...
> [INFO] Video stream started...
> 
> Does this mean that it only has the results from the 1st epoch? If so, why is that?

please check whether do you run the 'config_quick_testing.json' ? I rember that this file's epoch is 1.

**Comment by ghost** [comment]
> > > > Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?
> > > 
> > > 
> > > hi, what's the problem?
> > 
> > 
> > I've trained my model using 20 epochs but, and if I am not mistaken, it should save all of that to model_best_all.pth.tar (I am using the config_all.json file). But when I run webcam.py, it gives me this:
> > Using GPU for inference
> > => loaded checkpoint './model_best_all.pth.tar' (**epoch 1**)
> > [INFO] Attemping to start video stream...
> > [INFO] Video stream started...
> > Does this mean that it only has the results from the 1st epoch? If so, why is that?
> 
> please check whether do you run the 'config_quick_testing.json' ? I rember that this file's epoch is 1.
> 
> > > > Hi @eleow, is there any way for me to contact you to ask about your project that was forked from this one?
> > > 
> > > 
> > > hi, what's the problem?
> > 
> > 
> > I've trained my model using 20 epochs but, and if I am not mistaken, it should save all of that to model_best_all.pth.tar (I am using the config_all.json file). But when I run webcam.py, it gives me this:
> > Using GPU for inference
> > => loaded checkpoint './model_best_all.pth.tar' (**epoch 1**)
> > [INFO] Attemping to start video stream...
> > [INFO] Video stream started...
> > Does this mean that it only has the results from the 1st epoch? If so, why is that?
> 
> please check whether do you run the 'config_quick_testing.json' ? I rember that this file's epoch is 1.

I checked already. But the 'config_quick_testing.json' file's checkpoint is sent to **trainings/jpeg_model/jester_conv_4_classes/checkpoint.pth.tar**

Whereas the checkpoint for 'config_all.json' is sent to **./model_best_all.pth.tar**

So I dont think that's the problem. Do you have any other ideas as to why I'm not getting it?

**Comment by Coderx44** [comment]
> ## Hi, everyone, when I run train.py, I got a error as follow:
> (base) root@bf5f0cf0f3d5:/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master# python train.py --config configs/config_quick_testing.json --use_gpu=False => Output folder for this run -- jester_conv_4_classes
> 
> > Using 8 processes for data loader.
> > Training is getting started...
> > Training takes 1 epochs.
> > Current LR : 0.001
> > Traceback (most recent call last):
> > File "train.py", line 328, in 
> > main()
> > File "train.py", line 185, in main
> > val_loss, val_top1, val_top5 = validate(val_loader, model, criterion)
> > File "train.py", line 257, in validate
> > for i, (input, target) in enumerate(val_loader):
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in **next**
> > return self._process_next_batch(batch)
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
> > raise batch.exc_type(batch.exc_msg)
> > IndexError: Traceback (most recent call last):
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in 
> > samples = collate_fn([dataset[i] for i in batch_indices])
> > File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 38, in **getitem**
> > img_paths = self.get_frame_names(item.path)
> > File "/app/uda-code/CVND---Gesture-Recognition-master/CVND---Gesture-Recognition-master/data_loader.py", line 73, in get_frame_names
> > frame_names += [frame_names[-1]] * (num_frames_necessary - num_frames)
> > IndexError: list index out of range
> 
> I don't know what's wrong, I did not change any code. I'm very appreciated if anyone can give me some advice.

**Comment by Coderx44** [comment]
hey did you find any solution
